# -*- coding: utf-8 -*-
"""hello world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N7U_gGxUxi4NApgrzpzoYcR5CreQhn4s
"""

print("helllo world!")